### PR TITLE
added Resonator_7.2x3mm and tried to comply with the KiCad Library Conven...

### PR DESCRIPTION
**Pull request by KarlZeilhofer**
created on the example of this part:
Murata	CSTCC8M00G53-R0	
8MHz resonator, SMD, 0.5+0.3%
Farnell (Element 14) #1170435

### CODE REVIEW

**Comment by michal777** [comment]
Please modify silkscreen to make 1-pin marker visible after assembly. Examples: http://www.pcblibraries.com/forum/smt-library-silkscreen-outlines_topic26.html
Please add description in footprint properties (name of package, manufacturer, datasheet file name).

**Comment by KarlZeilhofer** [comment]
thanks for the hint! it was my first contribution :)

**Comment by KarlZeilhofer** [comment]
where do I find these fields for the description?
do you have a good example, where I can have a look?

**Comment by michal777** [comment]
In footprint properties there is field "Doc" (footprint properties icon or right click on footprint and "Edit Footprint")
Example is LQFP-52-1EP_10x10mm_Pitch0.65mm from Housings_QFP

**Comment by michal777** [comment]
Thanks, sorry for late reply. I've made some corrections according to kicad library convention.

**Pull request merged**
